#! /bin/bash
##
 # Copyright 2012 Adobe Systems Incorporated
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
##

bbndk="/Users/lorin/sdks/bb-ndk"
mobilespec="/Users/lorin/cordova/mobile-spec"
devicepin=24CC0D0B
deviceip=169.254.0.1
devicepass="password"

echo cd'ing into bb-ndk dir
cd $bbndk

echo running bbnkd-env
source bbndk-env_10_1_0_1020.sh

echo cd'ing into project dir
cd $1

echo adding target
./cordova/target add bb10 $deviceip device -p $devicepass --pin $devicepin

echo copying mobile spec
cp -r $mobilespec/* www/
